# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detectWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainDialog(object):
    def setupUi(self, MainDialog):
        MainDialog.setObjectName("MainDialog")
        MainDialog.resize(788, 621)
        MainDialog.setStyleSheet("background-color : rgb(0, 0, 17);color : rgb(0, 255, 255);\n")
        self.gridLayout = QtWidgets.QGridLayout(MainDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_label = QtWidgets.QCheckBox(MainDialog)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.checkBox_label.setFont(font)
        self.checkBox_label.setStyleSheet("background-color : rgb(0, 0, 17);color : rgb(0, 255, 255);\n"
"")
        self.checkBox_label.setObjectName("checkBox_label")
        self.gridLayout.addWidget(self.checkBox_label, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(MainDialog)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel { background-color : rgb(0, 0, 17); color : rgb(187, 255, 254);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 255, 255);}\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.table_statistics = QtWidgets.QTableWidget(MainDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_statistics.sizePolicy().hasHeightForWidth())
        self.table_statistics.setSizePolicy(sizePolicy)
        self.table_statistics.setMinimumSize(QtCore.QSize(220, 360))
        self.table_statistics.setMaximumSize(QtCore.QSize(330, 16777215))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.table_statistics.setFont(font)
        self.table_statistics.setFocusPolicy(QtCore.Qt.NoFocus)
        self.table_statistics.setStyleSheet("QHeaderView::section {\n"
"    background-color: rgb(0, 0, 17);\n"
"    color: rgb(255, 187, 0);\n"
"    padding-left: 4px;\n"
"    border: 2px solid rgb(0, 255, 255);\n"
"    font-weight: bold;\n"
"}\n"
"QTableWidget\n"
"{\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 255, 255);\n"
"color:rgb(187, 255, 254);\n"
"gridline-width:2px;\n"
"gridline-color: rgb(0, 255, 255);\n"
"}\n"
"\n"
"QTableView {\n"
"    selection-background-color: qlineargradient(x1: 0, y1: 0, x2: 1.0, y2: 1.0, stop: 0 rgb(34, 0, 85), stop: 1 white);\n"
"    selection-color: rgb(0, 255, 0);\n"
"}")
        self.table_statistics.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.table_statistics.setFrameShadow(QtWidgets.QFrame.Plain)
        self.table_statistics.setLineWidth(5)
        self.table_statistics.setShowGrid(True)
        self.table_statistics.setWordWrap(True)
        self.table_statistics.setCornerButtonEnabled(True)
        self.table_statistics.setColumnCount(2)
        self.table_statistics.setObjectName("label_statistics")
        self.table_statistics.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_statistics.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_statistics.setHorizontalHeaderItem(1, item)
        self.table_statistics.horizontalHeader().setVisible(False)
        self.table_statistics.horizontalHeader().setHighlightSections(False)
        self.table_statistics.horizontalHeader().setMinimumSectionSize(40)
        self.table_statistics.horizontalHeader().setSortIndicatorShown(True)
        self.table_statistics.horizontalHeader().setStretchLastSection(True)
        self.table_statistics.verticalHeader().setVisible(False)
        self.table_statistics.verticalHeader().setHighlightSections(False)
        self.table_statistics.verticalHeader().setSortIndicatorShown(False)
        self.horizontalLayout_2.addWidget(self.table_statistics)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.OpenButton = QtWidgets.QPushButton(MainDialog)
        self.OpenButton.setMinimumSize(QtCore.QSize(111, 51))
        self.OpenButton.setMaximumSize(QtCore.QSize(119, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.OpenButton.setFont(font)
        self.OpenButton.setStyleSheet("background-color : rgb(170, 0, 255);color : rgb(0, 255, 255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 255, 255);")
        self.OpenButton.setObjectName("OpenButton")
        self.horizontalLayout.addWidget(self.OpenButton)
        self.DetectButton = QtWidgets.QPushButton(MainDialog)
        self.DetectButton.setMinimumSize(QtCore.QSize(111, 51))
        self.DetectButton.setMaximumSize(QtCore.QSize(119, 16777215))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.DetectButton.setFont(font)
        self.DetectButton.setStyleSheet("background-color : rgb(0, 0, 17);color : rgb(0, 255, 255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 255, 255);")
        self.DetectButton.setObjectName("DetectButton")
        self.horizontalLayout.addWidget(self.DetectButton)
        self.label_msg = QtWidgets.QLabel(MainDialog)
        self.label_msg.setMinimumSize(QtCore.QSize(0, 51))
        self.label_msg.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label_msg.setFont(font)
        self.label_msg.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_msg.setStyleSheet("QLabel { background-color : rgb(0, 0, 17); color : rgb(187, 255, 254);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color: rgb(0, 255, 255);}\n"
"\n"
"")
        self.label_msg.setObjectName("label_msg")
        self.horizontalLayout.addWidget(self.label_msg)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)

        self.retranslateUi(MainDialog)
        QtCore.QMetaObject.connectSlotsByName(MainDialog)

    def retranslateUi(self, MainDialog):
        _translate = QtCore.QCoreApplication.translate
        MainDialog.setWindowTitle(_translate("MainDialog", "Dialog"))
        self.checkBox_label.setText(_translate("MainDialog", "Image Detection"))
        self.checkBox_label.setShortcut(_translate("MainDialog", "V"))
        self.label.setText(_translate("MainDialog", "<html><head/><body><p align=\"center\"><img src=\":/image/icon/glass_icon.jpg\"/><br/><span style=\" font-weight:600;\">Open an Image in Folder...</span></p></body></html>"))
        self.table_statistics.setSortingEnabled(False)
        item = self.table_statistics.horizontalHeaderItem(0)
        item.setText(_translate("MainDialog", "Name"))
        item = self.table_statistics.horizontalHeaderItem(1)
        item.setText(_translate("MainDialog", "Color"))
        self.OpenButton.setText(_translate("MainDialog", "Open Image"))
        self.DetectButton.setText(_translate("MainDialog", "Detect"))
        self.label_msg.setText(_translate("MainDialog", "<html><head/><body><p align=\"center\">designed by jin_jk </p></body></html>"))
import sources_rc
